---
game:
  game-directory: ... # full path to directory with installed game
  expansion: cataclysm # only 'cataclysm' and 'wotlk' are supported
  account:  # name of your account

companion:
  name:  # name of your companion
  class:  # class of your companion

open-ai:
  base_url:  # api url
  api_key:  # api key
