---
game:
  game-directory: ... # full path to directory with installed game. Use double backslashes \\ in Windows
  expansion: cataclysm # only 'cataclysm' and 'wotlk' are supported
  account:  # name of your account

companion:
  name:  # name of your companion
  class:  # class of your companion
